### ISSUE TITLE
Will GPT-J-6B be supported ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [minimaxir/aitextgen#140]
It provides on bar performance with GPT-3 (https://gpt3demo.com/apps/gpt-j-6b)

**Comment by swcrazyfan** [comment]
As a person working on fine-tuning GPT-J, it takes a whole lot more power to work with this bad boy. Technically, it will be possible to generate text from it eventually (probably sooner rather than later), but it'll be impossible to fine-tune in Colab.

Currently, I've fine-tuned a model that's technically compatible, but my Colab is crashing every time I try to load it. Apparently, someone has made a way to load the model into HuggingFace transformers, but my guess is we won't see actual support for GPT-J in aitextgen until HuggingFace supports it officially.

**Comment by minimaxir** [comment]
Not on the roadmap since there's no sane way to get it to fit into a GPU without severe compromises.
