### ISSUE TITLE
Best practices for dataset preparation to avoid MemoryError: Unable to allocate

### ISSUE THREAD

**Issue by DenisSergeevitch** [minimaxir/aitextgen#31]
I'm trying to train Reddit model and the problem that I have met is related to custom model training only.

I have exported ~500 Mb of Reddit comments to the *.txt file, from a custom list of **non-English** subs, and separated every publication with:
<|endoftext|>

Every section could contain thousands of comments.

The problem is that when I'm running tokenization I got an error after "Compute merges" stage:
`MemoryError: Unable to allocate 57.3 GiB for an array with shape (3126653, 9842) and data type uint16`.

I have tried to use *.csv instead with `line_by_line=True`, where every comment on a new line. After 50 000 steps on this csv dataset, I got a model that was "contextual" much worse than it was of 15 000 steps with txt file without `line_by_line=True`.

So, the question is: how is better to work with txt files and how much symbols should be inside one <|endoftext|> section.

My config:
`config = build_gpt2_config(vocab_size=10000, max_length=512, dropout=0.0, n_embd=512, n_layer=8, n_head=8)`
`data = TokenDataset(file_name, save_cache=True, vocab_file=vocab_file, merges_file=merges_file, block_size=512)`

If anyone has any ideas how to fix this, I would appreciate ✨

**Comment by minimaxir** [comment]
The `(3126653, 9842)` implies you are loading a text with `9842` tokens at some point in the pipeline, which is excessive since you are using a `max_length` of 512.

You should probably:

a) Filter out super-long comments in your dataset. 512 tokens is longer than the vast majority of Reddit comments, especially with a custom tokenizer to optimize it.
b) Format the dataset as a single-column `.csv`, where each comment is its own row. This is _required_ with Reddit comments because comments may have their own line breaks.

**Comment by DenisSergeevitch** [comment]
Thank you, I have fixed issue with tokens amount and it helped :)
