### ISSUE TITLE
Release 0.4 prediction different than previous release (under certain test case)

### ISSUE THREAD

**Issue by channelz** [minimaxir/aitextgen#92]
Test case 1:
Prompt : `<soq> What is`
Prediction : soq> What is .....

^the leading '<' is always trimmed away.  Did not preform this way in the previous release.

Test case 2:
Prompt : What is
Prediction : What is ...

The prediction is as expected.

**Comment by minimaxir** [comment]
In `0.4.0` I [added](https://github.com/minimaxir/aitextgen/blob/8dbc36244daf59c04d6a25f95fb409501d4a826d/aitextgen/aitextgen.py#L403) an `lstrip` param (default true) to strip whitespace from the beginning of the text: however, it appears `^\W+` is the wrong regex since it'll catch the leading `<`.

You can set `lstrip=False` to `generate()` for the time being but this should be fixed.
